### ISSUE TITLE
Unnecessary _send() function

### ISSUE THREAD

**Issue by dbns97** [electricimp/ImpPager#1]
`send()` just calls `_send()`. Not sure why both would be necessary (unless calling `_send()` elsewhere).

**Comment by ppetrosh** [comment]
Correct. send did more than just calling _send initially, but was simplified over time. Will clean it up.

Thanks for catching all these issues. Is any of them critical to you at this point?

**Comment by dbns97** [comment]
No, none critical. The changes I suggested shouldn't really change the functionality, just simplify it a bit mostly.

**Comment by ppetrosh** [comment]
Got it. This is what I thought too. Thanks.
