### ISSUE TITLE
Don't need to extend ConnectionManager

### ISSUE THREAD

**Issue by dbns97** [electricimp/ImpPager#4]
Instead of extending ConnectionManager, you could add an `onConnect()` (and `onDisconnect()`) method to ImpPager. E.g:
    `pager.onConnect(cb) {
        _cm.onConnect(function() {
            _scheduleRetryIfConnected();
            cb();
        }.bindenv(this));
    }`

Another option would be to allow for multiple callbacks in the ConnectionManager class.

**Comment by ppetrosh** [comment]
That's true. There are multiple ways to implement it. I just wanted to keep connection manager separate of ImpPager.

Just curious, do you see any issues with the current approach?

**Comment by dbns97** [comment]
The current approach should work fine, the reason I suggested the change is because it would remove and simplify a lot of the code and also, the user would then only need to create an instance of the ImpPager class and maybe the normal ConnectionManager class if they choose, which they may already know how to use.

**Comment by ppetrosh** [comment]
Got it. Thanks. I'll give it a look to see how it simplifies the code. But in general agree, one entity is easier to deal with than two.

**Comment by betzrhodes** [comment]
Closing since this issue relates to impPager and had been addressed
